# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: sha512


    role_hierarchy:
        ROLE_CHEF:  [ROLE_PROJET, ROLE_DEV]
        ROLE_DEV :  [ROLE_TACHE]
        ROLE_ADMIN:  [ROLE_CHEF, ROLE_DEV]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #in_memory:
         #   memory:
          #      users:
           #         developpeur: { password: developpeur, roles: [ 'ROLE_DEV' ]}
            #        chef_projet: { password: chefdeprojet, roles: [ 'ROLE_CHEF' ]}
        main:
            #entity:
             #   class: AppBundle\Entity\User
              #  property: username
            id: fos_user.user_provider.username_email

        fos_userbundle:
            id: fos_user.user_provider.username_email


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider:   main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /platform
            anonymous:    true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
